In [3]:
import numpy as np

In [7]:
# array indexing
nparr = np.arange(2, 20)
print(nparr[1])
print(nparr.size)

3
18


In [14]:
# slice array
arr1 = np.arange(1, 20)
arr_slice = slice(1, 20, 2)

print(arr1[arr_slice])

[ 2  4  6  8 10 12 14 16 18]


In [22]:
# slice array inline
arr2 = np.arange(1, 20)
print(arr2[2:])

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [21]:
# slice until specified index
print(arr2[:15])

[1 2 3 4 5 6 7 8 9]


In [26]:
# slicing of 2d array
arr3 = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(arr3[:2, :2])

[[1 2]
 [3 4]]


In [31]:
# array attributes
print(arr3.shape)
print(arr3.ndim)
print(arr3.size)
print(arr3.itemsize)

(3, 3)
2
9
8


In [32]:
# create uninitialized array
arr4 = np.empty([3,2], dtype=int)
print(arr4)

[[0 0]
 [0 0]
 [0 0]]


In [33]:
# create 1D array with zeros
arr5 = np.zeros(5)
print(arr5)

[0. 0. 0. 0. 0.]
